name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  docker_image: academy
  docker_tag: latest

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academy
          POSTGRES_PASSWORD: academy
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      uses: ./.github/actions/maven_build

    - name: Docker build
      uses: ./.github/actions/docker_build
      with:
        image_name: $docker_image
        tag_name: $docker_tag
    - name: Save the Docker build
      run: docker save -o ${{env.docker_image}}.tar  ${{env.docker_image}}:${{env.docker_tag}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.docker_image}}
        path: ${{env.docker_image}}.tar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to Docker Hub
      uses: ./.github/actions/docker_push
      with:
        docker_image:  ${{env.docker_image}}:${{env.docker_tag}}
        docker_username: ${{secrets.DOCKERHUB_USERNAME}}

  listImage:
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{env.docker_image}}
      - uses: actions/download-artifact@v4
      - run: docker load -i ${{env.docker_image}}.tar
      - name: Docker image list
        run: docker image ls
    needs: build